backend:
  name: test-repo

media_folder: static/img

publish_mode: editorial_workflow

collections:
  - name: posts
    label: Posts
    folder: /src/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: featuredImage, label: Image, widget: image }
      - {label: "Body", name: "body", widget: "markdown"}
